### ISSUE TITLE
Package is missing static files and template on pypi

### ISSUE THREAD

**Issue by crayxt** [wuttem/flask-dataview#1]
Hi,

Just noticed that your packaged archive on pypi only contains python files, without js and templates data.
Please consider adding MANIFEST.in file with recursive inclusion of js and html data.

Great idea of a package, by the way!

Thanks,

**Comment by wuttem** [comment]
Thanks you for the information! I wasn't aware of this.
I just build this for myself to visualize timeseries from a climate sensor.
Any feedback an what would be needed to make this library usable for others is welcome!
