### ISSUE TITLE
Secondary Y axis

### ISSUE THREAD

**Issue by crayxt** [wuttem/flask-dataview#4]
I wonder whether supporting secondary (and further) Y axis is planned? Or is it possible to do now?

I have 2 or more parameters with different ranges/units of measure, and I would like to plot them at one chart.

Sorry for asking such questions here, as there is no place to discuss.

Thanks,

**Comment by wuttem** [comment]
Added Secondary y axis in version 0.3
For now you can only choose it in settings menu (top right of chart).
